Add missing include
Fixes build on macOS:

/Users/runner/work/1/s/solvers-private/mp/include/mp/flat/std_constr.h:21:24: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    static std::string name { "LinCon" + RhsOrRange::name() };